services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
